### ISSUE TITLE
挂载路径问题

### ISSUE THREAD

**Issue by shiwentao1994** [AmbitiousJun/go-emby2alist#1]
配置了很多遍，试了很多不同挂载路径，最后还是无法正常使用，请求在各个软件的路径配置上出一个更详细的教程

**Comment by AmbitiousJun** [comment]
可以进 docker 日志看一下

```shell
docker logs -f go-emby2alist -n 1000
```

播放一个视频，然后在日志里边会打印 “尝试请求 Alist 资源：” 后边会跟上实际上请求 alist 的路径，你可以看看这个路径和你实际 alist 的路径是否匹配

**Comment by AmbitiousJun** [comment]
如果还是有疑惑的话，看看最新 README 文档上的示例图能不能帮上你

**Comment by shiwentao1994** [comment]
根据最新的图例，已经可以正常解析，但是使用网站、Fileball、VidHub测试，均无法正常播放
![屏幕截图 2024-09-05 194903](https://github.com/user-attachments/assets/be683d92-aba2-4637-83db-9047c1751d53)

**Comment by shiwentao1994** [comment]
网页端显示
![屏幕截图 2024-09-05 195933](https://github.com/user-attachments/assets/e399b934-3e02-4643-8259-d3878153c540)
Fileball，在转圈后显示
![微信图片_20240905200002](https://github.com/user-attachments/assets/84f5570e-a7df-40c7-9c27-62ae13a29e56)
VidHub显示
![微信图片_20240905195954](https://github.com/user-attachments/assets/1db35e39-866c-4d20-9bc8-d63f5db24c69)

**Comment by AmbitiousJun** [comment]
> 根据最新的图例，已经可以正常解析，但是使用网站、Fileball、VidHub测试，均无法正常播放 ![屏幕截图 2024-09-05 194903](https://private-user-images.githubusercontent.com/33592118/364763832-be683d92-aba2-4637-83db-9047c1751d53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NDA0NjIsIm5iZiI6MTcyNTU0MDE2MiwicGF0aCI6Ii8zMzU5MjExOC8zNjQ3NjM4MzItYmU2ODNkOTItYWJhMi00NjM3LTgzZGItOTA0N2MxNzUxZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEyNDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZWNiYjY0ZTE4ZDM2MjcwM2UxYTM0MzViZmE4ZGM2NmY3MWIxNjAyYjQ2ZmM3MzEzMDZjYzM4NTkzYzlkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zma7U4Jc_cxRgt70vrwbYpNog6SmCCH1CN7txcHsbB8)

从日志来看一切正常，只是 115 我没用过不太清楚，直接拿日志中打印的直链地址，放到其他播放器中可以播放吗

**Comment by AmbitiousJun** [comment]
可以的话你复制一个直链给我吧，我测试看看

**Comment by shiwentao1994** [comment]
https://cdnfhnfile.115.con/5f66df4ec0dea89516596da391c08f080cfee5f6/Home.Alone.1990.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.5.1-FGT.nkv7t-17284832368u-62503477&s-104857600&d-2354194968-e4k24gzt1j1dhzlqi-0&c=2&f=1&k-d591c9886a3630a6527d0f9c61386610&us-1048576000&uc=10&v=1，其它播放器测试过也不行

**Comment by AmbitiousJun** [comment]
> [https://cdnfhnfile.115.con/5f66df4ec0dea89516596da391c08f080cfee5f6/Home.Alone.1990.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.5.1-FGT.nkv7t-17284832368u-62503477&s-104857600&d-2354194968-e4k24gzt1j1dhzlqi-0&c=2&f=1&k-d591c9886a3630a6527d0f9c61386610&us-1048576000&uc=10&v=1，其它播放器测试过也不行](https://cdnfhnfile.115.con/5f66df4ec0dea89516596da391c08f080cfee5f6/Home.Alone.1990.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.5.1-FGT.nkv7t-17284832368u-62503477&s-104857600&d-2354194968-e4k24gzt1j1dhzlqi-0&c=2&f=1&k-d591c9886a3630a6527d0f9c61386610&us-1048576000&uc=10&v=1%EF%BC%8C%E5%85%B6%E5%AE%83%E6%92%AD%E6%94%BE%E5%99%A8%E6%B5%8B%E8%AF%95%E8%BF%87%E4%B9%9F%E4%B8%8D%E8%A1%8C)

试了一下一直被 403 禁止访问了，等我自己搭个 115 来试试看

**Comment by shiwentao1994** [comment]
好嘞，坐等反馈情况，明天有空，我搭个阿里云盘的试试，测试下

**Comment by shiwentao1994** [comment]
阿里云盘挂载已测试，一切正常

**Comment by AmbitiousJun** [comment]
> 好嘞，坐等反馈情况，明天有空，我搭个阿里云盘的试试，测试下

115 已适配，更新到测试版试试看

```shell
docker-compose down
git checkout main
git pull origin main
docker-compose up -d --build
```

Web 端由于跨域问题，不能直接播放 115 的直链，找到一个解决方法，你可以试试：https://github.com/bpking1/embyExternalUrl/issues/236

**Comment by shiwentao1994** [comment]
已测试，手机端正常播放，web端可以通过chrome安装[modify header](https://chromewebstore.google.com/detail/empty-title/idgpnmonknjnojddfkpgkljpfnnfcklj?utm_source=ext_app_menu)插件，导入如下代码解决
`[
    {
        "alwaysOn":true,
        "respHeaders":[
            {
                "enabled":true,
                "name":"Access-Control-Allow-Origin",
                "value":"*"
            }
        ],
        "shortTitle":"1",
        "title":"CORS Support",
        "urlFilters":[
            {
                "enabled":true,
                "urlRegex":"*.115.com"
            }
        ],
        "version":2
    }
]`
