### ISSUE TITLE
能不能支持strm直链

### ISSUE THREAD

**Issue by yating1022** [AmbitiousJun/go-emby2alist#11]
我strm里面是http开头的直链，能不能支持直接把strm里面的链接替换给客户端

**Comment by AmbitiousJun** [comment]
strm 我还没研究过，先加入开发计划里边吧，不过应该没这么快能支持上

先用这个 nginx 版本的反代服务试试，https://github.com/bpking1/embyExternalUrl

**Comment by AmbitiousJun** [comment]
strm 已加入支持，可切换到测试版尝鲜使用，或者等下个正式版发布

**Comment by yating1022** [comment]
> strm 已加入支持，可切换到测试版尝鲜使用，或者等下个正式版发布

感谢
