### ISSUE TITLE
无法显示海报问题

### ISSUE THREAD

**Issue by chanho0** [AmbitiousJun/go-emby2alist#14]
Q&A已解答，已知必须改为外网可访问的emby地址
因无公网ipv4地址，有域名ddns绑定公网ipv6地址，填入后无法正常访问8095
请问是没适配ipv6还是docker网络需要改别的模式

**Comment by AmbitiousJun** [comment]
看起来这种静态资源 308 重定向的模式还是比较局限

我下个版本把它替换成本地代理的形式吧，你现在有 ssl 证书吗，可以先弄成 https 的，应该就正常了

**Comment by AmbitiousJun** [comment]
已经将 http 服务器的静态资源处理方式调整为本地代理，可切换到测试版尝鲜使用，或者等下个正式版本发布
