### ISSUE TITLE
局域网内调用外部播放器仍走server流量

### ISSUE THREAD

**Issue by chanho0** [AmbitiousJun/go-emby2alist#15]
问题：局域网内使用nginx端口链接emby server，调用外部播放器（potplayer、mxplayer）仍走server流量上传，假如使用emby theatre或者emby app则不会走流量，抓取链接发现emby给外部播放器传入的为内网地址:8096，有没有办法截取该部分修改，谢谢

**Comment by AmbitiousJun** [comment]
不太能 get 到你的问题，你是指 go-emby2alist 通过 nginx 间接连接 emby server，会导致最终访问的是 8096 吗
还是一些调用第三方播放器的脚本，弹出来的播放器，播放的是 8096

**Comment by chanho0** [comment]
仅限局域网内go-emby2alist 通过 nginx 间接连接 emby server，调用第三方播放器播放是8096

**Comment by AmbitiousJun** [comment]
日志有没有报什么错，有可能是代理异常重定向回源了
