### ISSUE TITLE
emby非管理员权限的用户播放提示401

### ISSUE THREAD

**Issue by yimshing** [AmbitiousJun/go-emby2alist#19]
非管理员权限的用户用fileball和senplayer播放会提示401错误，直到在emby后台打开允许该用户管理服务器才能正常播放

**Comment by AmbitiousJun** [comment]
日志有没有报什么错

我自己的话一直是使用非管理员用户观看的，不用给管理权限。
出现 401 错误的话是客户端发送的 api key 服务端不认识。可以尝试 fileball 删除 emby 服务器之后再重新连接

**Comment by yimshing** [comment]
似乎没啥异常，就是要给管理权限才能看，不然就提示401，其他播放器也一样，不止fileball，试过删除配置再播放，还是提示401
2024/11/04 00:28:46 监听端口: 8095, 匹配路由: .*
[GIN] 2024/11/04 - 00:28:46 | 200 |    2.774733ms |    192.168.16.1 | GET      "/emby/Users/c2672d358bfb473aa1dce7174b50fbd2/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CProductionYear%2CStatus%2CEndDate%2CCanDelete&GroupItems=true&Limit=16&ParentId=81851"
2024/11/04 00:28:46 监听端口: 8095, 匹配路由: .*
[GIN] 2024/11/04 - 00:28:46 | 200 |    8.978364ms |    192.168.16.1 | GET      "/emby/Users/c2672d358bfb473aa1dce7174b50fbd2/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CProductionYear%2CStatus%2CEndDate%2CCanDelete&GroupItems=true&Limit=16&ParentId=198460"
2024/11/04 00:28:46 监听端口: 8095, 匹配路由: .*
[GIN] 2024/11/04 - 00:28:46 | 200 |    5.046035ms |    192.168.16.1 | GET      "/emby/Users/c2672d358bfb473aa1dce7174b50fbd2/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CProductionYear%2CStatus%2CEndDate%2CCanDelete&GroupItems=true&Limit=16&ParentId=69972"
2024/11/04 00:28:46 监听端口: 8095, 匹配路由: .*
[GIN] 2024/11/04 - 00:28:46 | 200 |   43.275244ms |    192.168.16.1 | GET      "/emby/Users/c2672d358bfb473aa1dce7174b50fbd2/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CProductionYear%2CStatus%2CEndDate%2CCanDelete&GroupItems=true&Limit=16&ParentId=95190"
2024/11/04 00:28:47 监听端口: 8095, 匹配路由: .*
[GIN] 2024/11/04 - 00:28:47 | 200 |    9.472575ms |    192.168.16.1 | GET      "/emby/Users/c2672d358bfb473aa1dce7174b50fbd2/Items/Latest?EnableImageTypes=Primary%2CBackdrop%2CThumb&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CProductionYear%2CStatus%2CEndDate%2CCanDelete&GroupItems=true&Limit=16&ParentId=202964"
[GIN] 2024/11/04 - 00:28:53 | 401 |    1.038928ms |    192.168.16.1 | GET      "/emby/Users/c2672d358bfb473aa1dce7174b50fbd2/Items/609810"
[GIN] 2024/11/04 - 00:28:59 | 401 |    1.253082ms |    192.168.16.1 | GET      "/emby/Users/c2672d358bfb473aa1dce7174b50fbd2/Items/522634"
2024/11/04 00:28:59 监听端口: 8095, 匹配路由: (?i)^/.*images
[GIN] 2024/11/04 - 00:28:59 | 200 |   96.666937ms |    192.168.16.1 | GET      "/emby/Items/522634/Images/Backdrop?maxWidth=1320&tag=96841862dd34018b5978dd62ef0c8221&quality=90

**Comment by AmbitiousJun** [comment]
http://{your emby host}:8096/emby/Auth/Keys?api_key=c64379e2d7e549129aa56712a8f202da

用浏览器访问一下这个地址，使用非管理员权限用户的 api key (web 登录非管理员账号后用这个方法抓取 key: https://github.com/AmbitiousJun/go-emby2alist?tab=readme-ov-file#%E5%85%B3%E4%BA%8E-emby-%E7%9A%84-api_key)
看看响应是不是：User guest does not have access to ManageServer feature.

**Comment by yimshing** [comment]
使用非管理员权限用户的 api key 浏览http://{your emby host}:8096/emby/Auth/Keys?api_key=非管理员权限用户的 api key
有以下提示，我的是http，emby服务端版本4.7.14.0
User does not have admin access.

**Comment by AmbitiousJun** [comment]
那真有可能是 api 不兼容，可以看看响应码是什么吗

**Comment by yimshing** [comment]
请问怎么看响应码呀？ 是下面这个吗?
http://{your emby host}:8096/emby/Users/778bce40a8b04bbc961e11ef9c86b5ce/Items/636037?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=306f91f3-24f8-47b3-a545-c39f769aebf4&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=58ba9bab28854e50b6c85fa851cfbe65&X-Emby-Language=zh-cn 401 (Unauthorized)

**Comment by AmbitiousJun** [comment]
可以浏览器访问一下刚刚说的那个 api，然后打开浏览器的控制台进入网络选项卡，然后再刷新一下页面，看看请求结果如何：
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/b912ec7b-3c3f-4957-8e9d-b3b17295a935">

**Comment by yimshing** [comment]
Status Code:
401 Unauthorized

**Comment by AmbitiousJun** [comment]
那就是接口问题了，我找找看有没有其他的兼容的接口
麻烦再试试看这个吧，按照刚才的方法看一下响应码是 403 还是 401：
http://{your emby host}:8096/emby/ScheduledTasks?api_key=c643728e53229e3a4b8f202da

**Comment by AmbitiousJun** [comment]
顺便再看看直接调用这个接口：http://{your emby host}:8096/emby/Auth/Keys，不传递 api key
看看浏览器响应的文本是不是：Access token is invalid or expired.

**Comment by yimshing** [comment]
> 那就是接口问题了，我找找看有没有其他的兼容的接口 麻烦再试试看这个吧，按照刚才的方法看一下响应码是 403 还是 401： http://{your emby host}:8096/emby/ScheduledTasks?api_key=c643728e53229e3a4b8f202da

Request URL:
http://{your emby host}:8096/emby/ScheduledTasks?api_key=58ba9bab28854e50b6c85fa851cfbe65
Request Method:
GET
Status Code:
401 Unauthorized
Remote Address:
127.0.0.1:10809
Referrer Policy:
strict-origin-when-cross-origin

**Comment by yimshing** [comment]
> /emby/Auth/Keys

确实是Access token is invalid or expired.

**Comment by AmbitiousJun** [comment]
好的 感谢 那我就用这个进一步判断了

**Comment by yimshing** [comment]
> 好的 感谢 那我就用这个进一步判断了

感谢作者，希望项目越来越棒，有需要我服务器信息的话可以私聊我
