### ISSUE TITLE
无法显示海报

### ISSUE THREAD

**Issue by ruoai520** [AmbitiousJun/go-emby2alist#2]
重定向没问题 但是无法显示海报，不使用8095端口 直连emby正常 请求解决

**Comment by AmbitiousJun** [comment]
1. 使用什么客户端访问的
2. 是公网 ip 吗
3. 确保配置 `emby.host` 中配置的 ip 是可以在其他设备的浏览器上直接访问到
4. 是否会使用浏览器的控制台调试，在 8095 端口用控制台抓一个海报的 url，然后新开一个标签页直接访问这个 url 看看最终被重定向到什么地址上，和 emby 源服务器上的 url 是否一致
