### ISSUE TITLE
关于直链文件名变更问题 

### ISSUE THREAD

**Issue by zeltp** [AmbitiousJun/go-emby2alist#28]
关于之前的问题,测试错误,开启直链参数转发后,网页端依旧无法播放,手机端问题解决,麻烦再次查看,上次开放的测试地址目前依旧有效
[https://github.com/AmbitiousJun/go-emby2alist/issues/24](url)

**Comment by AmbitiousJun** [comment]
我现在看了一下那个链接 guest 用户已无法正常访问
要不你单独开一个账号然后发送到我的邮箱吧：1535820771@qq.com

**Comment by zeltp** [comment]
已经发送

**Comment by AmbitiousJun** [comment]
已收到 我找时间看看

**Comment by AmbitiousJun** [comment]
我看了一下 是因为你这个直链地址 `yun.mcloud.139.com` 不允许跨域导致的 web 端无法正常播放，其他播放器应该是能正常播的吧？

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/32246e53-22ba-4233-8965-708032fb0e24" />

如果想在 web 上看的话可以尝试借助插件，参考一下这里 https://github.com/AmbitiousJun/go-emby2alist/issues/1#issuecomment-2334045987

**Comment by zeltp** [comment]
是的，其他播放器正常
![20241224-003122](https://github.com/user-attachments/assets/c2c93f56-9da1-4aa0-b8d4-24b715bc006b)
请问下我这个设置有无问题，，目前以这个设置依旧无法播放

**Comment by AmbitiousJun** [comment]
我这边可以正常播的：
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/4edebd26-846d-49fe-828a-e07651762059" />

我的配置：
<img width="598" alt="image" src="https://github.com/user-attachments/assets/dc99ebbf-79b5-40e5-979c-ebea310bc946" />

还有一点需要注意的是，strm 直链和 go-emby2alist 的安全级别要兼容，
比如 go-emby2alist 开启了 ssl 证书，但是 strm 里边的直链地址是普通 http 的话就不能正常播放视频

**Comment by zeltp** [comment]
感谢，可以正常播放了，如有可能是否考虑把该功能集成而无需再通过浏览器插件实现

**Comment by AmbitiousJun** [comment]
> 感谢，可以正常播放了，如有可能是否考虑把该功能集成而无需再通过浏览器插件实现

跨域这个问题没法在反代服务这里解决，现在知道的好像就 3 种方式：
1. 浏览器插件
2. 直链地址自己进行跨域适配
3. 修改 emby 的 web 源代码

**Comment by zeltp** [comment]
我有使用过隔壁的(https://github.com/bpking1/embyExternalUrl) 的emby2alist,未出现跨域问题，应该是已经进行跨域适配，
关于第三点可以给点思路嘛，我想研究一下

**Comment by AmbitiousJun** [comment]
我去看了一下 确实是有人提出一种反代服务能实现的方案：https://github.com/chen3861229/embyExternalUrl/issues/64
你的 alist 地址是否还可用？我找时间测试一下

**Comment by AmbitiousJun** [comment]
地址还可用，感谢。已经适配了 js 脚本补丁到反代服务上，下个版本修复这个问题

**Comment by AmbitiousJun** [comment]
虽然做了跨域适配 但是仍然会有概率被这个 139 地址 403 拦截导致无法播放：
<img width="492" alt="image" src="https://github.com/user-attachments/assets/f907a972-de9a-474e-b7c5-206bcd5804cf" />

暂时不清楚原因

**Comment by zeltp** [comment]
感谢，目前已经更新到最新版本，还有个问题，图片质量配置是通过什么方法实现的？我未更改它的默认值时，设备出现卡死重启的情况，我将他改为100后并无问题，并且图片的加载速度更快，我是使用路由器挂载的，型号京东百里云，arm 4核处理器，1G运存，如果是设备原因，建议增加下说明

**Comment by AmbitiousJun** [comment]
> 感谢，目前已经更新到最新版本，还有个问题，图片质量配置是通过什么方法实现的？我未更改它的默认值时，设备出现卡死重启的情况，我将他改为100后并无问题，并且图片的加载速度更快，我是使用路由器挂载的，型号京东百里云，arm 4核处理器，1G运存，如果是设备原因，建议增加下说明

那看来这个配置还是得根据自身实际情况来配置，其实就是反代修改了请求 emby 服务器图片接口的质量参数，设备卡死估计是图片太多 emby 服务器处理不过来了
