### ISSUE TITLE
字幕好像无法加载？

### ISSUE THREAD

**Issue by TheWuSi** [AmbitiousJun/go-emby2alist#3]
使用emby win小秘频道的版本，字幕好像没办法加载出来，是外挂字幕

**Comment by AmbitiousJun** [comment]
原画播放吗

**Comment by TheWuSi** [comment]
是的，原画播放，可以识别到字幕，但是播放就是没办法显示，外部播放器也不行，内置也不行

**Comment by AmbitiousJun** [comment]
好的 我排查一下

**Comment by AmbitiousJun** [comment]
> 是的，原画播放，可以识别到字幕，但是播放就是没办法显示，外部播放器也不行，内置也不行

临时解决方法，把转码功能关闭 => `videoPreview.enable` 设置为 false

下个版本修复

**Comment by TheWuSi** [comment]
感谢您

**Comment by TheWuSi** [comment]
需要重新编译吗？

**Comment by AmbitiousJun** [comment]
不需要，重启容器就行

**Comment by TheWuSi** [comment]
好的

**Comment by TheWuSi** [comment]
好像还是看不到

**Comment by AmbitiousJun** [comment]
> 好像还是看不到

那等等下个版本吧，这两天测试没问题我就发了

**Comment by TheWuSi** [comment]
好的

**Comment by AmbitiousJun** [comment]
字幕加载不出来貌似是因为 emby 会把源文件整个都加载到服务器后再去解析出字幕文件
你看看是不是这个原因，一个视频播放，然后选好字幕，等个一两分钟的，看看字幕会不会出来

**Comment by AmbitiousJun** [comment]
有字幕的资源还是推荐使用第三方播放器吧，fileball，mxplayer 小秘版都是秒加载
emby这个字幕机制。。。

**Comment by TheWuSi** [comment]
好像是这样的，字幕要先在服务器缓存才会在客户端放，现在都可以放了，前提把那个配置关掉，现在web fileball infuse都可以字幕了
