### ISSUE TITLE
Installation on Windows 11

### ISSUE THREAD

**Issue by lequan2909** [AmbitiousJun/go-emby2alist#4]
I installed Emby and AList on Windows and installed go-emby2alist on Docker.
AList: http://localhost:5244/
Emby: http://localhost:8096/

The drive is mapped to drive H:/

So, is my configuration correct?"

emby:
  host: http://localhost:8096           
  mount-path: H:/                        
  api-key: 56b4f........... 
  episodes-unplay-prior: true               
alist:
  host: http://localhost:8096            
  token: alist-..................                         
video-preview:
  enable: true                               
  containers:                               
    - mp4
    - mkv
path:
  emby2alist: 
    - /Phim4K:/Phim4K

**Comment by AmbitiousJun** [comment]
I haven't mounted a cloud disk on windows, so if H:/ works, it's best, but if not, try /h (not sure 🫤)

**Comment by lequan2909** [comment]
> I haven't mounted a cloud disk on windows, so if H:/ works, it's best, but if not, try /h (not sure 🫤)
Thank you for your response, the setup I used is working.

**Comment by lequan2909** [comment]
> I haven't mounted a cloud disk on windows, so if H:/ works, it's best, but if not, try /h (not sure 🫤)

Thank you for your response, the setup I used is working.

**Comment by lequan2909** [comment]
@AmbitiousJun 
Sorry for the inconvenience, although I coded it to work, but on the actual server, even though I fixed the mount-path, the issue still occurred

2024-09-19 00:24:37 2024/09/19 01:24:37 代理接口失败: alistFilePath 解析异常: H:\Phim4K\The.Lockdown.2024.2160p.WEB-DL.DDP5.1.DV.HDR.H.265-FLUX.mkv, error: 字符串不包含 /: H:\Phim4K\The.Lockdown.2024.2160p.WEB-DL.DDP5.1.DV.HDR.H.265-FLUX.mkv, 重定向回源服务器处理

What can I do to improve it?

**Comment by AmbitiousJun** [comment]
> @AmbitiousJun Sorry for the inconvenience, although I coded it to work, but on the actual server, even though I fixed the mount-path, the issue still occurred
> 
> 2024-09-19 00:24:37 2024/09/19 01:24:37 代理接口失败: alistFilePath 解析异常: H:\Phim4K\The.Lockdown.2024.2160p.WEB-DL.DDP5.1.DV.HDR.H.265-FLUX.mkv, error: 字符串不包含 /: H:\Phim4K\The.Lockdown.2024.2160p.WEB-DL.DDP5.1.DV.HDR.H.265-FLUX.mkv, 重定向回源服务器处理
> 
> What can I do to improve it?

This is due to the program not being well adapted to Windows. I will fix it in the beta version. You can try changing emby.mount from H:/ to H: and see if it works.

**Comment by lequan2909** [comment]
I fixed the issue by manually replacing the "splitFromSecondSlash" function in the "internal/service/path/path.go" file

// splitFromSecondSlash 找到给定字符串 str 中第二个 '/' 字符的位置
// 并以该位置为首字符切割剩余的子串返回
func splitFromSecondSlash(str string) (string, error) {
	// Replace backslashes with forward slashes
	str = strings.ReplaceAll(str, "\\", "/")

	firstIdx := strings.Index(str, "/")
	if firstIdx == -1 {
		return "", fmt.Errorf("字符串不包含 /: %s", str)
	}

	secondIdx := strings.Index(str[firstIdx+1:], "/")
	if secondIdx == -1 {
		return "", fmt.Errorf("字符串只有单个 /: %s", str)
	}

	return str[secondIdx+firstIdx+1:], nil
}

**Comment by AmbitiousJun** [comment]
> I fixed the issue by manually replacing the "splitFromSecondSlash" function in the "internal/service/path/path.go" file
> 
> ```
> // splitFromSecondSlash 找到给定字符串 str 中第二个 '/' 字符的位置
> // 并以该位置为首字符切割剩余的子串返回
> func splitFromSecondSlash(str string) (string, error) {
> 	// Replace backslashes with forward slashes
> 	str = strings.ReplaceAll(str, "\\", "/")
> 
> 	firstIdx := strings.Index(str, "/")
> 	if firstIdx == -1 {
> 		return "", fmt.Errorf("字符串不包含 /: %s", str)
> 	}
> 
> 	secondIdx := strings.Index(str[firstIdx+1:], "/")
> 	if secondIdx == -1 {
> 		return "", fmt.Errorf("字符串只有单个 /: %s", str)
> 	}
> 
> 	return str[secondIdx+firstIdx+1:], nil
> }
> ```

Yes, the adaptation here is not done. Thank you for raising the issue, and I will fix it in the next version.
