### ISSUE TITLE
提问-通过这个方式在有svip情况下可以绕过aliyun第三方权益包么？

### ISSUE THREAD

**Issue by Asunfly** [AmbitiousJun/go-emby2alist#6]
提问-通过这个方式在有svip情况下可以绕过aliyun第三方权益包么？

**Comment by AmbitiousJun** [comment]
我的账号是svip和三方权益包都开通了，不太好测试
不过经过这段时间测试观察发现看转码版本的时候好像不会消耗三方权益包流量
至于限速这个我就测不了了，你可以直接在alist上试试
