### ISSUE TITLE
有两个问题跟大佬反馈一下

### ISSUE THREAD

**Issue by bilili-syy** [AmbitiousJun/go-emby2alist#7]
1.当alist挂载115网盘调用直链的时候,用emby网页端直接播放提示无法兼容的流,安卓端正常

2.当看一个视频之后返回,或者有时候点视频会emby会提示。前者我基本上点击的所有视频返回都有这个提示。后者出现没有这么频繁
![image](https://github.com/user-attachments/assets/704bc7b2-c82e-4a64-ad79-3c4ad8cbd72b)

**Comment by AmbitiousJun** [comment]
第一个问题是浏览器跨域，可以尝试通过浏览器插件解决，参考这里 #1 

第二个问题不够具体，下次遇到的话可以看看docker日志中是否有错误输出，把日志一并贴出来，感谢

**Comment by bilili-syy** [comment]
感谢您解答第一个问题 这是第二个问题日志
`2024/10/02 18:59:45 [38;2;228;116;112m手动请求 PlaybackInfo 失败: Post "http://eb2.siyangyuan.gq:5208/Items/27663/PlaybackInfo?api_key=14f6087301774834817a8408f1b6cdeb&reqformat=json": read tcp 192.168.31.76:54521->27.10.40.65:5208: wsarecv: An existing connection was forcibly closed by the remote host., 不更新 Items 信息[0m
[GIN] 2024/10/02 - 18:59:45 |[97;42m 200 [0m|     70.5738ms |  123.147.249.72 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items/27663?fields=ShareLevel%2CSyncStatus%2CContainerSyncStatus&ExcludeFields=VideoChapters%2CVideoMediaSources%2CMediaStreams&X-Emby-Client=Emby+for+Android&X-Emby-Device-Name=23127PN0CC&X-Emby-Device-Id=6bf1fb3a973ddee1&X-Emby-Client-Version=3.4.20&X-Emby-Token=14f6087301774834817a8408f1b6cdeb&X-Emby-Language=zh-cn"
2024/10/02 18:59:45 headers to encode cacheKey:  [38;2;220;165;080mX-Real-Ip=123.147.249.72;Sec-Ch-Ua-Mobile=?1;Priority=u=1, i;Sec-Ch-Ua-Platform="Android";X-Forwarded-Host=eb2.siyangyuan.gq:5208;X-Forwarded-Port=16666;X-Forwarded-Proto=https;Content-Type=text/plain;X-Requested-With=com.mb.android;Content-Length=2196;X-Real-Proto=https;User-Agent=Mozilla/5.0 (Linux; Android 14; 23127PN0CC Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.71 Mobile Safari/537.36;Sec-Fetch-Mode=cors;Sec-Fetch-Site=cross-site;Sec-Ch-Ua="Not/A)Brand";v="8", "Chromium";v="126", "Android WebView";v="126";Sec-Fetch-Dest=empty;[0m
[GIN] 2024/10/02 - 18:59:45 |[97;42m 200 [0m|     13.2386ms |  123.147.249.72 |[97;46m POST    [0m "/emby/Items/27663/PlaybackInfo?UserId=6cc58bd062dc4a4b8fa3e0dd34f1d556&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=11174800&X-Emby-Client=Emby+for+Android&X-Emby-Device-Name=23127PN0CC&X-Emby-Device-Id=6bf1fb3a973ddee1&X-Emby-Client-Version=3.4.20&X-Emby-Token=14f6087301774834817a8408f1b6cdeb&X-Emby-Language=zh-cn&reqformat=json"`
我是通过nginx将内网地址反代到:http://eb2.siyangyuan.gq:5208

**Comment by AmbitiousJun** [comment]
涉及到网络的问题我本地还不好测试，除了这个日志还有其他的吗，特别是http响应码是4开头的

**Comment by bilili-syy** [comment]
这是我从请求开始到出现错误结束的全部日志
`[GIN] 2024/10/03 - 09:04:58 |[97;42m 200 [0m|      9.5029ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556?X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
2024/10/03 09:04:58 [38;2;090;156;248m匹配路由: ^/$|(?i)^.*(/web|/users|/artists|/genres|/similar|/shows|/system|/remote|/scheduledtasks)[0m
2024/10/03 09:04:58 [38;2;090;156;248m匹配路由: ^/$|(?i)^.*(/web|/users|/artists|/genres|/similar|/shows|/system|/remote|/scheduledtasks)[0m
[GIN] 2024/10/03 - 09:04:58 |[97;42m 200 [0m|     23.1741ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items?Fields=PrimaryImageAspectRatio&Recursive=true&IncludeItemTypes=Playlist&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
[GIN] 2024/10/03 - 09:04:58 |[97;42m 200 [0m|      9.8753ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items?Fields=PrimaryImageAspectRatio&Recursive=true&IncludeItemTypes=BoxSet&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
2024/10/03 09:04:58 [38;2;090;156;248m匹配路由: ^/$|(?i)^.*(/web|/users|/artists|/genres|/similar|/shows|/system|/remote|/scheduledtasks)[0m
2024/10/03 09:04:58 [38;2;090;156;248m匹配路由: ^/$|(?i)^.*(/web|/users|/artists|/genres|/similar|/shows|/system|/remote|/scheduledtasks)[0m
2024/10/03 09:04:58 [38;2;090;156;248m匹配路由: ^/$|(?i)^.*(/web|/users|/artists|/genres|/similar|/shows|/system|/remote|/scheduledtasks)[0m
2024/10/03 09:04:58 [38;2;090;156;248m匹配路由: ^/$|(?i)^.*(/web|/users|/artists|/genres|/similar|/shows|/system|/remote|/scheduledtasks)[0m
[GIN] 2024/10/03 - 09:04:58 |[97;42m 200 [0m|     11.7376ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items/Resume?Recursive=true&Fields=BasicSyncInfo%2CCanDelete%2CPrimaryImageAspectRatio%2CProductionYear&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&MediaTypes=Video&Limit=12&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
[GIN] 2024/10/03 - 09:04:58 |[97;42m 200 [0m|      9.1898ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items/Resume?Recursive=true&Fields=BasicSyncInfo%2CCanDelete%2CPrimaryImageAspectRatio%2CProductionYear&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&MediaTypes=Audio&Limit=12&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
2024/10/03 09:04:58 [38;2;090;156;248m匹配路由: ^/$|(?i)^.*(/web|/users|/artists|/genres|/similar|/shows|/system|/remote|/scheduledtasks)[0m
[GIN] 2024/10/03 - 09:04:58 |[97;42m 200 [0m|     12.8825ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items/Latest?Limit=16&Fields=BasicSyncInfo%2CCanDelete%2CPrimaryImageAspectRatio%2CProductionYear&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=28199&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
[GIN] 2024/10/03 - 09:04:58 |[97;42m 200 [0m|     15.3441ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items/Latest?Limit=16&Fields=BasicSyncInfo%2CCanDelete%2CPrimaryImageAspectRatio%2CProductionYear%2CStatus%2CEndDate&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=28132&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
[GIN] 2024/10/03 - 09:04:58 |[97;42m 200 [0m|     43.3487ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items/Latest?Limit=16&Fields=BasicSyncInfo%2CCanDelete%2CPrimaryImageAspectRatio%2CProductionYear&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=28376&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
2024/10/03 09:04:58 [38;2;090;156;248m匹配路由: (?i)^/.*images[0m
[GIN] 2024/10/03 - 09:04:58 |[90;47m 308 [0m|      1.3883ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Items/28438/Images/Backdrop?maxWidth=334&tag=2dc836c284c38e3cc4481c284f4c6665&quality=70"
2024/10/03 09:04:59 [38;2;090;156;248m匹配路由: (?i)^/.*users/.*/items/\d+($|\?)[0m
[GIN] 2024/10/03 - 09:04:59 |[97;42m 200 [0m|      18.059ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items/28376?X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
2024/10/03 09:04:59 [38;2;090;156;248m匹配路由: ^/$|(?i)^.*(/web|/users|/artists|/genres|/similar|/shows|/system|/remote|/scheduledtasks)[0m
[GIN] 2024/10/03 - 09:04:59 |[97;42m 200 [0m|     26.8979ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items?IncludeItemTypes=Movie&Fields=BasicSyncInfo%2CCanDelete%2CPrimaryImageAspectRatio%2CProductionYear%2CStatus%2CEndDate&StartIndex=0&SortBy=SortName&SortOrder=Ascending&ParentId=28376&EnableImageTypes=Primary%2CBackdrop%2CThumb&ImageTypeLimit=1&Recursive=true&Limit=50&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
2024/10/03 09:05:00 [38;2;090;156;248m匹配路由: (?i)^/.*users/.*/items/\d+($|\?)[0m
2024/10/03 09:05:00 [38;2;090;156;248mitemInfo 解析结果: {"PlaybackInfoUri":"/Items/28434/PlaybackInfo?api_key=1a30c2b040994f7bb0cbf65b3ec527b3&reqformat=json","ApiKey":"1a30c2b040994f7bb0cbf65b3ec527b3","Id":"28434","MsInfo":{"Empty":true,"Transcode":false,"OriginId":"","Format":"","AlistPath":"","TemplateId":"","SourceNamePrefix":"","RawId":""}}[0m
2024/10/03 09:05:00 headers to encode cacheKey:  [38;2;220;165;080mUser-Agent=Go-http-client/1.1;Content-Length=4055;Content-Type=text/plain;[0m
[GIN] 2024/10/03 - 09:05:00 |[97;42m 200 [0m|      4.3377ms |   192.168.31.76 |[97;46m POST    [0m "/Items/28434/PlaybackInfo?api_key=1a30c2b040994f7bb0cbf65b3ec527b3&reqformat=json"
2024/10/03 09:05:00 [38;2;228;116;112m手动请求 PlaybackInfo 失败: invalid character '1' in string escape code, 不更新 Items 信息[0m
[GIN] 2024/10/03 - 09:05:00 |[97;42m 200 [0m|     23.7437ms |  192.168.31.112 |[97;44m GET     [0m "/emby/Users/6cc58bd062dc4a4b8fa3e0dd34f1d556/Items/28434?fields=ShareLevel&ExcludeFields=VideoChapters%2CVideoMediaSources%2CMediaStreams&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn"
2024/10/03 09:05:00 headers to encode cacheKey:  [38;2;220;165;080mUser-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0;Content-Type=text/plain;Content-Length=4306;[0m
2024/10/03 09:05:00 [38;2;090;156;248m匹配路由: (?i)^/.*items/.*/playbackinfo\??[0m
2024/10/03 09:05:00 [38;2;090;156;248mItemInfo 解析结果: {"MsInfo":{"OriginId":"","AlistPath":"","TemplateId":"","Format":"","SourceNamePrefix":"","RawId":"","Transcode":false,"Empty":true},"PlaybackInfoUri":"/Items/28434/PlaybackInfo?api_key=1a30c2b040994f7bb0cbf65b3ec527b3&reqformat=json","ApiKey":"1a30c2b040994f7bb0cbf65b3ec527b3","Id":"28434"}[0m
2024/10/03 09:05:00 [38;2;090;156;248m复用缓存空间中的 PlaybackInfo 信息, itemId: 28434[0m
[GIN] 2024/10/03 - 09:05:00 |[97;42m 200 [0m|      6.2019ms |  192.168.31.112 |[97;46m POST    [0m "/emby/Items/28434/PlaybackInfo?UserId=6cc58bd062dc4a4b8fa3e0dd34f1d556&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=200000000&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=dae170c6-b760-4dac-9290-0d56ff765b29&X-Emby-Client-Version=4.9.0.30&X-Emby-Token=1a30c2b040994f7bb0cbf65b3ec527b3&X-Emby-Language=zh-cn&reqformat=json"`

**Comment by AmbitiousJun** [comment]
方便协助我测试一下吗，
就是使用 http 请求工具，比如 postman，发送一个请求，然后将响应发给我看一下：

请求方法：POST
请求路径：${你的协议域名端口}/Items/28434/PlaybackInfo?api_key=1a30c2b040994f7bb0cbf65b3ec527b3&reqformat=json
请求体类型：text/plain
请求体：{"DeviceProfile":{"MaxStaticBitrate":140000000,"MaxStreamingBitrate":140000000,"MusicStreamingTranscodingBitrate":192000,"DirectPlayProfiles":[{"Container":"mp4,m4v","Type":"Video","VideoCodec":"h264,h265,hevc,av1,vp8,vp9","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"mkv","Type":"Video","VideoCodec":"h264,h265,hevc,av1,vp8,vp9","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"flv","Type":"Video","VideoCodec":"h264","AudioCodec":"aac,mp3"},{"Container":"3gp","Type":"Video","VideoCodec":"","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"mov","Type":"Video","VideoCodec":"h264","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"opus","Type":"Audio"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3"},{"Container":"mp2,mp3","Type":"Audio","AudioCodec":"mp2"},{"Container":"m4a","AudioCodec":"aac","Type":"Audio"},{"Container":"mp4","AudioCodec":"aac","Type":"Audio"},{"Container":"flac","Type":"Audio"},{"Container":"webma,webm","Type":"Audio"},{"Container":"wav","Type":"Audio","AudioCodec":"PCM_S16LE,PCM_S24LE"},{"Container":"ogg","Type":"Audio"},{"Container":"webm","Type":"Video","AudioCodec":"vorbis,opus","VideoCodec":"av1,VP8,VP9"}],"TranscodingProfiles":[{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Streaming","Protocol":"hls","MaxAudioChannels":"2","MinSegments":"1","BreakOnNonKeyFrames":true},{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"opus","Type":"Audio","AudioCodec":"opus","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"wav","Type":"Audio","AudioCodec":"wav","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"opus","Type":"Audio","AudioCodec":"opus","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"wav","Type":"Audio","AudioCodec":"wav","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mkv","Type":"Video","AudioCodec":"mp3,aac,opus,flac,vorbis","VideoCodec":"h264,h265,hevc,av1,vp8,vp9","Context":"Static","MaxAudioChannels":"2","CopyTimestamps":true},{"Container":"ts","Type":"Video","AudioCodec":"mp3,aac","VideoCodec":"h264,h265,hevc,av1","Context":"Streaming","Protocol":"hls","MaxAudioChannels":"2","MinSegments":"1","BreakOnNonKeyFrames":true,"ManifestSubtitles":"vtt"},{"Container":"webm","Type":"Video","AudioCodec":"vorbis","VideoCodec":"vpx","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp4","Type":"Video","AudioCodec":"mp3,aac,opus,flac,vorbis","VideoCodec":"h264","Context":"Static","Protocol":"http"}],"ContainerProfiles":[],"CodecProfiles":[{"Type":"VideoAudio","Codec":"aac","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"VideoAudio","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"Video","Codec":"h264","Conditions":[{"Condition":"EqualsAny","Property":"VideoProfile","Value":"high|main|baseline|constrained baseline|high 10","IsRequired":false},{"Condition":"LessThanEqual","Property":"VideoLevel","Value":"62","IsRequired":false}]},{"Type":"Video","Codec":"hevc","Conditions":[{"Condition":"EqualsAny","Property":"VideoCodecTag","Value":"hvc1|hev1|hevc|hdmv","IsRequired":false}]}],"SubtitleProfiles":[{"Format":"vtt","Method":"Hls"},{"Format":"eia_608","Method":"VideoSideData","Protocol":"hls"},{"Format":"eia_708","Method":"VideoSideData","Protocol":"hls"},{"Format":"vtt","Method":"External"},{"Format":"ass","Method":"External"},{"Format":"ssa","Method":"External"}],"ResponseProfiles":[{"Type":"Video","Container":"m4v","MimeType":"video/mp4"}]}}

**Comment by bilili-syy** [comment]
`{
    "MediaSources": [
        {
            "Chapters": [
                {
                    "StartPositionTicks": 0,
                    "Name": "章节 1",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 0
                },
                {
                    "StartPositionTicks": 3000000000,
                    "Name": "章节 2",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 1
                },
                {
                    "StartPositionTicks": 6000000000,
                    "Name": "章节 3",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 2
                },
                {
                    "StartPositionTicks": 9000000000,
                    "Name": "章节 4",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 3
                },
                {
                    "StartPositionTicks": 12000000000,
                    "Name": "章节 5",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 4
                },
                {
                    "StartPositionTicks": 15000000000,
                    "Name": "章节 6",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 5
                },
                {
                    "StartPositionTicks": 18000000000,
                    "Name": "章节 7",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 6
                },
                {
                    "StartPositionTicks": 21000000000,
                    "Name": "章节 8",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 7
                },
                {
                    "StartPositionTicks": 24000000000,
                    "Name": "章节 9",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 8
                },
                {
                    "StartPositionTicks": 27000000000,
                    "Name": "章节 10",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 9
                },
                {
                    "StartPositionTicks": 30000000000,
                    "Name": "章节 11",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 10
                },
                {
                    "StartPositionTicks": 33000000000,
                    "Name": "章节 12",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 11
                },
                {
                    "StartPositionTicks": 36000000000,
                    "Name": "章节 13",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 12
                },
                {
                    "StartPositionTicks": 39000000000,
                    "Name": "章节 14",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 13
                },
                {
                    "StartPositionTicks": 42000000000,
                    "Name": "章节 15",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 14
                },
                {
                    "StartPositionTicks": 45000000000,
                    "Name": "章节 16",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 15
                },
                {
                    "StartPositionTicks": 48000000000,
                    "Name": "章节 17",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 16
                },
                {
                    "StartPositionTicks": 51000000000,
                    "Name": "章节 18",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 17
                },
                {
                    "StartPositionTicks": 54000000000,
                    "Name": "章节 19",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 18
                },
                {
                    "StartPositionTicks": 57000000000,
                    "Name": "章节 20",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 19
                },
                {
                    "StartPositionTicks": 60000000000,
                    "Name": "章节 21",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 20
                },
                {
                    "StartPositionTicks": 63000000000,
                    "Name": "章节 22",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 21
                },
                {
                    "StartPositionTicks": 66000000000,
                    "Name": "章节 23",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 22
                },
                {
                    "StartPositionTicks": 69000000000,
                    "Name": "章节 24",
                    "MarkerType": "Chapter",
                    "ChapterIndex": 23
                }
            ],
            "Protocol": "File",
            "Id": "mediasource_28434",
            "Path": "G:\\115\\ali\\涩涩\\av\\#整理完成\\河北彩花\\[SONE-266-UC] 「請接吻…」这里我删了一点标题有点擦边\\SONE-266-UC.mp4",
            "Type": "Default",
            "Container": "mp4",
            "Size": 6826285381,
            "Name": "SONE-266-UC",
            "IsRemote": false,
            "HasMixedProtocols": false,
            "RunTimeTicks": 71785360000,
            "SupportsTranscoding": true,
            "SupportsDirectStream": true,
            "SupportsDirectPlay": true,
            "IsInfiniteStream": false,
            "RequiresOpening": false,
            "RequiresClosing": false,
            "RequiresLooping": false,
            "SupportsProbing": false,
            "MediaStreams": [
                {
                    "Codec": "hevc",
                    "CodecTag": "hev1",
                    "Language": "und",
                    "ColorTransfer": "bt709",
                    "ColorPrimaries": "bt709",
                    "ColorSpace": "bt709",
                    "TimeBase": "1/60000",
                    "VideoRange": "SDR",
                    "DisplayTitle": "1080p HEVC",
                    "IsInterlaced": false,
                    "BitRate": 7335651,
                    "BitDepth": 8,
                    "RefFrames": 1,
                    "IsDefault": true,
                    "IsForced": false,
                    "IsHearingImpaired": false,
                    "Height": 1080,
                    "Width": 1920,
                    "AverageFrameRate": 59.94006,
                    "RealFrameRate": 59.94006,
                    "Profile": "Main",
                    "Type": "Video",
                    "AspectRatio": "16:9",
                    "Index": 0,
                    "IsExternal": false,
                    "IsTextSubtitleStream": false,
                    "SupportsExternalStream": false,
                    "Protocol": "File",
                    "PixelFormat": "yuv420p",
                    "Level": 123,
                    "IsAnamorphic": false,
                    "ExtendedVideoType": "None",
                    "ExtendedVideoSubType": "None",
                    "ExtendedVideoSubTypeDescription": "None",
                    "AttachmentSize": 0
                },
                {
                    "Codec": "aac",
                    "CodecTag": "mp4a",
                    "Language": "und",
                    "TimeBase": "1/48000",
                    "DisplayTitle": "AAC stereo (默认)",
                    "IsInterlaced": false,
                    "ChannelLayout": "stereo",
                    "BitRate": 256129,
                    "Channels": 2,
                    "SampleRate": 48000,
                    "IsDefault": true,
                    "IsForced": false,
                    "IsHearingImpaired": false,
                    "Profile": "LC",
                    "Type": "Audio",
                    "Index": 1,
                    "IsExternal": false,
                    "IsTextSubtitleStream": false,
                    "SupportsExternalStream": false,
                    "Protocol": "File",
                    "ExtendedVideoType": "None",
                    "ExtendedVideoSubType": "None",
                    "ExtendedVideoSubTypeDescription": "None",
                    "AttachmentSize": 0
                }
            ],
            "Formats": [],
            "Bitrate": 7607440,
            "RequiredHttpHeaders": {},
            "AddApiKeyToDirectStreamUrl": false,
            "ReadAtNativeFramerate": false,
            "DefaultAudioStreamIndex": 1,
            "ItemId": "28434"
        }
    ],
    "PlaySessionId": "5a0ed013d6a4411289c376f2f503f73b"
}`

**Comment by AmbitiousJun** [comment]
尝试修复了一下，可以切换到测试版试试看
